name: Merge Pull Request
description: |
  This action merges a specified pull request.
  If [auto-merge][auto-merge] is enabled for the repository,
  the pull request will be merged automatically once all required reviews are approved and all status checks pass.

  ## Usage

  ```yaml
    steps:
      - name: Merge Pull Request
        uses: tmknom/merge-pull-request-action@v0
        with:
          pull-request: 10
  ```

inputs:
  pull-request:
    required: true
    description: Specifies the pull request to merge as a `number`, `url`, or `branch`.

outputs:
  auto-merge:
    value: ${{ steps.repository.outputs.auto-merge }}
    description: Indicates whether the auto-merge setting is enabled for the repository.

runs:
  using: composite

  steps:
    - name: Describe repository settings
      id: repository
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        echo "::group::Describe repository settings"
        set -x
        auto_merge="$(gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "/repos/${GITHUB_REPOSITORY}" \
          --jq '.allow_auto_merge')"
        echo "auto-merge=${auto_merge}" >> "${GITHUB_OUTPUT}"
        echo "::endgroup::"
      shell: bash

    - name: Merge
      env:
        PULL_REQUEST: ${{ inputs.pull-request }}
        AUTO_MERGE: ${{ steps.repository.outputs.auto-merge }}
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        echo "::group::Merge"
        set -x
        declare -a flags=(--merge --delete-branch)
        if [[ "${AUTO_MERGE}" == "true" ]]; then
          flags+=(--auto)
        fi
        gh pr merge "${PULL_REQUEST}" "${flags[@]}"
        echo "::endgroup::"
      shell: bash
